# Report generation utilities for AeroGuard AI

def format_report(analysis):
    """
    Formats the AI response into a readable emergency report.
    """
    return f"""
🚨 AeroGuard AI Emergency Report

{analysis}

Generated by AeroGuard AI
Powered by Google Gemma
"""
